name: Package and Publish VS Code Extension 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      INITIAL_VERSION: 1.0.3  # Define your initial version here

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    # Read and increment version number
    - name: Increment version number
      id: bump_version
      run: |
        VERSION="${{ env.INITIAL_VERSION }}"
        echo "Current version: $VERSION"
        NEW_VERSION=$(echo $VERSION | awk -F. -v OFS=. '{$NF++;print}')
        echo "New version: $NEW_VERSION"
        echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV

    # Update package.json with the new version number
    - name: Update package.json version
      run: npm version ${{ env.VERSION }} --no-git-tag-version

    # Package the VS Code extension
    - name: Package extension
      run: |
        npm install -g vsce
        vsce package

    # Publish the VS Code extension
    - name: Publish extension
      run: vsce publish
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}

    # Upload the packaged extension as an artifact
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: vscode-extension
        path: ./*.vsix
